"""initial migration

Revision ID: a9810abfaf97
Revises: 
Create Date: 2026-02-14 09:39:25.491590

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'a9810abfaf97'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_User_Table_email'), table_name='User_Table')
    op.drop_index(op.f('ix_User_Table_user_id'), table_name='User_Table')
    op.drop_table('User_Table')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('User_Table',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('email', mysql.VARCHAR(length=121), nullable=True),
    sa.Column('user_id', mysql.VARCHAR(length=15), nullable=True),
    sa.Column('username', mysql.TEXT(), nullable=True),
    sa.Column('password', mysql.TEXT(), nullable=True),
    sa.Column('profile_photo', mysql.TEXT(), nullable=True),
    sa.Column('slug', mysql.TEXT(), nullable=True),
    sa.Column('is_activated', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_User_Table_user_id'), 'User_Table', ['user_id'], unique=True)
    op.create_index(op.f('ix_User_Table_email'), 'User_Table', ['email'], unique=True)
    # ### end Alembic commands ###
